/**
 * HTI Bot API
 * Interact with the HTI Bot Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BaseSuccessModel model module.
 * @module model/BaseSuccessModel
 * @version 1.0.0
 */
class BaseSuccessModel {
    /**
     * Constructs a new <code>BaseSuccessModel</code>.
     * @alias module:model/BaseSuccessModel
     */
    constructor() { 
        
        BaseSuccessModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BaseSuccessModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BaseSuccessModel} obj Optional instance to populate.
     * @return {module:model/BaseSuccessModel} The populated <code>BaseSuccessModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BaseSuccessModel();

            if (data.hasOwnProperty('resultCode')) {
                obj['resultCode'] = ApiClient.convertToType(data['resultCode'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BaseSuccessModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BaseSuccessModel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * HTTP Status Code
 * @member {Number} resultCode
 */
BaseSuccessModel.prototype['resultCode'] = undefined;






export default BaseSuccessModel;

