/**
 * HTI Bot API
 * Interact with the HTI Bot Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RateConversation200Response model module.
 * @module model/RateConversation200Response
 * @version 1.0.0
 */
class RateConversation200Response {
    /**
     * Constructs a new <code>RateConversation200Response</code>.
     * @alias module:model/RateConversation200Response
     */
    constructor() { 
        
        RateConversation200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RateConversation200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RateConversation200Response} obj Optional instance to populate.
     * @return {module:model/RateConversation200Response} The populated <code>RateConversation200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RateConversation200Response();

            if (data.hasOwnProperty('resultCode')) {
                obj['resultCode'] = ApiClient.convertToType(data['resultCode'], 'Number');
            }
            if (data.hasOwnProperty('incidentReport')) {
                obj['incidentReport'] = ApiClient.convertToType(data['incidentReport'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RateConversation200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RateConversation200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['incidentReport'] && !(typeof data['incidentReport'] === 'string' || data['incidentReport'] instanceof String)) {
            throw new Error("Expected the field `incidentReport` to be a primitive type in the JSON string but got " + data['incidentReport']);
        }

        return true;
    }


}



/**
 * The result code
 * @member {Number} resultCode
 */
RateConversation200Response.prototype['resultCode'] = undefined;

/**
 * If the user has closed the conversation, an incident report on the conversation is generated.
 * @member {String} incidentReport
 */
RateConversation200Response.prototype['incidentReport'] = undefined;






export default RateConversation200Response;

