/**
 * HTI Bot API
 * Interact with the HTI Bot Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateKnowledgeDB200Response model module.
 * @module model/UpdateKnowledgeDB200Response
 * @version 1.0.0
 */
class UpdateKnowledgeDB200Response {
    /**
     * Constructs a new <code>UpdateKnowledgeDB200Response</code>.
     * @alias module:model/UpdateKnowledgeDB200Response
     */
    constructor() { 
        
        UpdateKnowledgeDB200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateKnowledgeDB200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateKnowledgeDB200Response} obj Optional instance to populate.
     * @return {module:model/UpdateKnowledgeDB200Response} The populated <code>UpdateKnowledgeDB200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateKnowledgeDB200Response();

            if (data.hasOwnProperty('resultCode')) {
                obj['resultCode'] = ApiClient.convertToType(data['resultCode'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateKnowledgeDB200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateKnowledgeDB200Response</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * The result code
 * @member {Number} resultCode
 */
UpdateKnowledgeDB200Response.prototype['resultCode'] = undefined;






export default UpdateKnowledgeDB200Response;

