/**
 * HTI Bot API
 * Interact with the HTI Bot Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BaseErrorModel from './model/BaseErrorModel';
import GetAnswer200Response from './model/GetAnswer200Response';
import HasOpenConversation200Response from './model/HasOpenConversation200Response';
import LanguageEnum from './model/LanguageEnum';
import UpdateKnowledgeDB200Response from './model/UpdateKnowledgeDB200Response';
import DefaultApi from './api/DefaultApi';


/**
* Interact with the HTI Bot Backend.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var HtiBotApi = require('index'); // See note below*.
* var xxxSvc = new HtiBotApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new HtiBotApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new HtiBotApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new HtiBotApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BaseErrorModel model constructor.
     * @property {module:model/BaseErrorModel}
     */
    BaseErrorModel,

    /**
     * The GetAnswer200Response model constructor.
     * @property {module:model/GetAnswer200Response}
     */
    GetAnswer200Response,

    /**
     * The HasOpenConversation200Response model constructor.
     * @property {module:model/HasOpenConversation200Response}
     */
    HasOpenConversation200Response,

    /**
     * The LanguageEnum model constructor.
     * @property {module:model/LanguageEnum}
     */
    LanguageEnum,

    /**
     * The UpdateKnowledgeDB200Response model constructor.
     * @property {module:model/UpdateKnowledgeDB200Response}
     */
    UpdateKnowledgeDB200Response,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
