/**
 * HTI Bot API
 * Interact with the HTI Bot Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HtiBotApi);
  }
}(this, function(expect, HtiBotApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HtiBotApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('continueConversation', function() {
      it('should call continueConversation successfully', function(done) {
        //uncomment below and update the code to test continueConversation
        //instance.continueConversation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAnswer', function() {
      it('should call getAnswer successfully', function(done) {
        //uncomment below and update the code to test getAnswer
        //instance.getAnswer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('hasOpenConversation', function() {
      it('should call hasOpenConversation successfully', function(done) {
        //uncomment below and update the code to test hasOpenConversation
        //instance.hasOpenConversation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rateConversation', function() {
      it('should call rateConversation successfully', function(done) {
        //uncomment below and update the code to test rateConversation
        //instance.rateConversation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateKnowledgeDB', function() {
      it('should call updateKnowledgeDB successfully', function(done) {
        //uncomment below and update the code to test updateKnowledgeDB
        //instance.updateKnowledgeDB(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
